version: 0.2

phases:
  pre_build:
    commands:
      - npm install -g npm@latest
      - npm cache clean --force
      - rm -rf node_modules package-lock.json
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
      - node_modules/**/*
      - app/**/*
      - index.js
      - ormconfig.js
      - ecosystem.config.js
      - package.json
      - tsconfig.json
      - .ebextensions/**/*
      - .platform/**/*
cache:
  paths:
    - node_modules/**/*
